Repository iiitl/MessEase, pull requests merged in 2025-03, with the labels that each got.

#12 Fixes issue #9: Changed screenOrientation of SplashScreen to portrait
  .idea/appInsightsSettings.xml
  .idea/compiler.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
Labels: accepted-15

#16 Added KDoc to Mess.kt
  app/src/main/java/com/theayushyadav11/MessEase/utils/Mess.kt
Labels: accepted-25

#17 Issue 3
  .idea/runConfigurations.xml
  app/src/main/java/com/theayushyadav11/MessEase/MainActivity.kt
  app/src/main/java/com/theayushyadav11/MessEase/ui/more/SettingsActivity.kt
  app/src/main/java/com/theayushyadav11/MessEase/ui/splash/SplashScreen.kt
  app/src/main/java/com/theayushyadav11/MessEase/utils/Mess.kt
  app/src/main/res/layout/activity_edit_complete.xml
  app/src/main/res/layout/activity_menu.xml
  app/src/main/res/layout/activity_show_menu.xml
  app/src/main/res/layout/comments_layout.xml
  app/src/main/res/layout/fragment_view_votes.xml
Labels: accepted-30

#21 Fixes issue #20: Added functional confirm password field in fragment_sign_up.xml
  app/src/main/java/com/theayushyadav11/MessEase/ui/splash/fragments/SignUpFragment.kt
  app/src/main/res/layout/fragment_sign_up.xml
Labels: accepted-30

#23 Fixes issue #10: Added designation icon in mess committee main page depending upon designation
  .idea/appInsightsSettings.xml
  app/src/main/java/com/theayushyadav11/MessEase/ui/MessCommittee/fragments/McMainPage.kt
  app/src/main/res/layout/fragment_mc_main_page.xml
Labels: accepted-25

#22 Fixes issue #13: Enhanced UI/UX of PaymentActivity adding Lottie Animations and Purpose text field
  app/src/main/java/com/theayushyadav11/MessEase/ui/more/PaymentActivity.kt
  app/src/main/res/layout/activity_payment.xml
  app/src/main/res/raw/payment_animation.json
Labels: accepted-45

#27 Added some images and fix their proportions
  README.md
Labels: accepted-25
